import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, Moirai_One, Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const moiraiOne = Moirai_One({
  weight: "400",
  variable: "--font-moirai-one",
  subsets: ["latin"],
});

const zenMaruGothic = Zen_Maru_Gothic({
  weight: "400",
  variable: "--font-zen-maru-gothic",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="caramellatte">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${moiraiOne.variable} ${zenMaruGothic.variable} antialiased bg-base-100 text-base-content min-h-screen`}
        style={{ fontFamily: "var(--font-zen-maru-gothic), sans-serif" }}
      >
        <header className="navbar bg-base-100 shadow-sm">
          <Link
            href="/"
            className="text-4xl font-extrabold tracking-wide italic drop-shadow-lg"
            style={{ fontFamily: "var(--font-moirai-one), sans-serif" }}
          >
            Happa
          </Link>
        </header>
        {children}
        <div className="dock">
    <button>
      <svg className="size-[1.2em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <g fill="currentColor" strokeLinejoin="miter" strokeLinecap="butt">
          <polyline
            points="1 11 12 2 23 11"
            fill="none"
            stroke="currentColor"
            strokeMiterlimit="10"
            strokeWidth="2"
          ></polyline>
          <path
            d="m5,13v7c0,1.105.895,2,2,2h10c1.105,0,2-.895,2-2v-7"
            fill="none"
            stroke="currentColor"
            strokeLinecap="square"
            strokeMiterlimit="10"
            strokeWidth="2"
          ></path>
          <line
            x1="12"
            y1="22"
            x2="12"
            y2="18"
            fill="none"
            stroke="currentColor"
            strokeLinecap="square"
            strokeMiterlimit="10"
            strokeWidth="2"
          ></line>
        </g>
      </svg>
      <span className="dock-label">Home</span>
    </button>

    <button className="//dock-active">
      <svg className="size-[1.2em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <g fill="currentColor" strokeLinejoin="miter" strokeLinecap="butt">
          <polyline
            points="3 14 9 14 9 17 15 17 15 14 21 14"
            fill="none"
            stroke="currentColor"
            strokeMiterlimit="10"
            strokeWidth="2"
          ></polyline>
          <rect
            x="3"
            y="3"
            width="18"
            height="18"
            rx="2"
            ry="2"
            fill="none"
            stroke="currentColor"
            strokeLinecap="square"
            strokeMiterlimit="10"
            strokeWidth="2"
          ></rect>
        </g>
      </svg>
      <span className="dock-label">Inbox</span>
    </button>

    <button>
      <svg className="size-[1.2em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <g fill="currentColor" strokeLinejoin="miter" strokeLinecap="butt">
          <circle
            cx="12"
            cy="12"
            r="3"
            fill="none"
            stroke="currentColor"
            strokeLinecap="square"
            strokeMiterlimit="10"
            strokeWidth="2"
          ></circle>
          <path
            d="m22,13.25v-2.5l-2.318-.966c-.167-.581-.395-1.135-.682-1.654l.954-2.318-1.768-1.768-2.318.954c-.518-.287-1.073-.515-1.654-.682l-.966-2.318h-2.5l-.966,2.318c-.581.167-1.135.395-1.654.682l-2.318-.954-1.768,1.768.954,2.318c-.287.518-.515,1.073-.682,1.654l-2.318.966v2.5l2.318.966c.167.581.395,1.135.682,1.654l-.954,2.318,1.768,1.768,2.318-.954c.518.287,1.073.515,1.654.682l.966,2.318h2.5l.966-2.318c.581-.167,1.135-.395,1.654-.682l2.318.954,1.768-1.768-.954-2.318c.287-.518.515-1.073.682-1.654l2.318-.966Z"
            fill="none"
            stroke="currentColor"
            strokeLinecap="square"
            strokeMiterlimit="10"
            strokeWidth="2"
          ></path>
        </g>
      </svg>
      <span className="dock-label">Settings</span>
    </button>
  </div>
      </body>
    </html>
  );
}
